//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD
    {
        public int sno { get; set; }
        public Nullable<decimal> AccountnO { get; set; }
        public string Mode { get; set; }
        public string Rupees { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<decimal> Interestrate { get; set; }
        public string Maturitydate { get; set; }
        public Nullable<decimal> Maturityamount { get; set; }
        public string Startdate { get; set; }
    }
}
