//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bankingdbEntities : DbContext
    {
        public bankingdbEntities()
            : base("name=bankingdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<debit> debits { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<userTable> userTables { get; set; }
        public virtual DbSet<TransferTabel> TransferTabels { get; set; }
        public virtual DbSet<deposit> deposits { get; set; }
        public virtual DbSet<FD> FDs { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
